### ISSUE TITLE
how to set a folder?

### ISSUE THREAD

**Issue by fawzib** [gebn/Brush#8]
pastebin allows you to set folders now.

**Comment by gebn** [comment]
Hi Fawzi, thanks for this and your other issue! I’m afraid I don’t have much time to add features to this library, but would be happy to review a pull request.

**Comment by gebn** [comment]
Taking another look at this, the [API docs](https://pastebin.com/api) make no mention of folders. I asked Pastebin, and they got back to me with:

> ...folders are currently not fully supported in the API, but it will be added in the future. We do not have an exact date for this yet though.

Closing this for the time being as it cannot currently be implemented, and there is no timeline for that changing. Please feel free to open another issue if/when you notice support is added!
